### PR TITLE
improved the functions of spp_oauth module

### LINKED ISSUE #602: DCI API is not working
**Describe the bug**
the module DCI API can be installed in openspp but is not working. postman is unable to retrieve data from openspp.
**To Reproduce**
1. Request a postman collection from developer
2. Instal DCI API module
3. Get credentials from DCI API (client id and client secret)
4. In postman go to `POST get access token` request body tab, paste client ID and secret 
5. click send. notice internal server error is returned in postman
**Expected behavior**
access token and token type should be displayed
**Screenshots**

**Additional context**

🔔 Note: This ticket should address common considerations without including country-specific content. Please ensure all references are generic and applicable across various contexts.

### PR DESCRIPTION
**Pull request by reichie020212**
## **Why is this change needed?**

DCI API is having an error because the RSA Keys are not injected in the ssh of the instance.

## **How was the change implemented?**

Changed the implementation of getting the RSA Keys

## **New unit tests**

None

## **Unit tests executed by the author**

spp_oauth/tests/test_rsa_encode_decode.py::TestRSA

## **How to test manually**

- Go to Apps menu and install the module `OpenSPP DCI API Server`
- Go to Settings -> DCI API Client Credentials.
- Create a credential
- Click `Show` button to view the Client ID and Client Secret.
- Copy and Paste the credentials somewhere (notepad, sublime, etc.)
- Use this credential to the API Collection.

## **Related links**
https://github.com/OpenSPP/openspp-modules/issues/602

### CODE REVIEW

**Comment by kneckinator** [comment]
Rebased on current 17.0 to be able to test with everything in 17.0

**Comment by kneckinator** [comment]
@reichie020212 when installing `spp_import_dci_api` I get this error:
```
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x74c62b1a86a0>: Failed to resolve 'dci.opencrvs.lab.cdpi.dev' ([Errno -3] Temporary failure in name resolution)
```

Full traceback:
```
2024-10-01 14:06:11,548 1 ERROR devel odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x74c62b1a86a0>: Failed to resolve 'dci.opencrvs.lab.cdpi.dev' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dci.opencrvs.lab.cdpi.dev', port=443): Max retries exceeded with url: /.well-known/locations.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x74c62b1a86a0>: Failed to resolve 'dci.opencrvs.lab.cdpi.dev' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 280, in _tag_function
    _eval_xml(self, rec, env)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 205, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/spp_import_dci_api/models/fetch_crvs_beneficiary.py", line 204, in create_locations
    response = requests.get(url, timeout=constants.REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dci.opencrvs.lab.cdpi.dev', port=443): Max retries exceeded with url: /.well-known/locations.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x74c62b1a86a0>: Failed to resolve 'dci.opencrvs.lab.cdpi.dev' ([Errno -3] Temporary failure in name resolution)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/modules/registry.py", line 114, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/opt/odoo/custom/src/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 627, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 693, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/opt/odoo/custom/src/odoo/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /opt/odoo/auto/addons/spp_import_dci_api/data/crvs_location_data.xml:4, somewhere inside
<function model="spp.crvs.location" name="create_locations"/>
```

**Comment by reichie020212** [comment]
@kneckinator based on the traceback you provided, it seems that the https://dci.opencrvs.lab.cdpi.dev/.well-known/locations.json was down the time you install the module `spp_import_dci_api`. Now, upon checking, i can access the url https://dci.opencrvs.lab.cdpi.dev/.well-known/locations.json and also able to install `spp_import_dci_api` without any issue.

Can you try again to install the module on your end? Thanks.

**Comment by reichie020212** [comment]
@kneckinator I'll try to improve the code to still proceed the installation even if the url https://dci.opencrvs.lab.cdpi.dev/.well-known/locations.json is not accessible

**Comment by reichie020212** [comment]
@kneckinator done improving the function

**Review by gonzalesedwin1123 — APPROVED** [review]

**Comment by kneckinator** [comment]
> https://dci.opencrvs.lab.cdpi.dev/.well-known/locations.json

Thanks. It appeared there are some issues with network routing in the openspp-docker container which was blocking outgoing connections to basically everything except *.google.com. I will investigate this a bit more.

A question on the `create_locations` method: if the name resolution fails during the installation of the component, or the service is down, is it possible to trigger this function manually later?

**Comment by reichie020212** [comment]
@kneckinator yes it is possible by upgrading the module.

**Review by kneckinator — APPROVED** [review]
LGTM 🎉 
Thanks @reichie020212

**Pull request merged**
