### PR TITLE
[IMP] test coverage

### PR DESCRIPTION
**Pull request by nhatnm0612**
## What this PR does?
For #202 
Improving the test coverage of SPP

#### Process:
- [x] spp_area *[marked since already have tests]*
- [x] spp_change_request
- [x] spp_consent
- [ ] spp_custom_field *[only 1 function `fields_view_get`]*
- [ ] spp_custom_field_custom_filter *[only edited views]*
- [ ] spp_custom_fields_ui 
- [ ] spp_custom_filter
- [ ] spp_data_export *[only controller]*
- [x] spp_event_data
- [x] spp_event_demo *[marked since already have tests]*
- [x] spp_idpass
- [x] spp_idqueue
- [x] spp_rest_auth_jwt
- [ ] spp_scan_id_document *[only javascript code]*
- [x] spp_service_points

### CODE REVIEW

**Comment by nhatnm0612** [comment]
**spp_idpass**: several errors made the test running fails:
- missing dependencies : `g2p_registry_membership` *[fixed]*
- missing dependencies : `spp_idqueue` *[skipTest since adding this to depends will create circular depends, leave there for future improvements]*
- `test_02_check_existing_id_not_existed` : failed by [this line of code](https://github.com/OpenSPP/openspp-registry/blob/dbeb14badda05b3c7f84b2ad7238114f88821cf5/spp_idpass/models/registrant.py#L244) *[fixed]*
- `test_04_send_idpass_parameters_correct_vals_response_403 ` : failed by [this line of code](https://github.com/OpenSPP/openspp-registry/blob/dbeb14badda05b3c7f84b2ad7238114f88821cf5/spp_idpass/models/registrant.py#L183) *[fixed]*

**Comment by nhatnm0612** [comment]
**spp_idqueue**: several errors made the test running fails:
- `test_02_compute_target_type ` : failed by [this line of code](https://github.com/OpenSPP/openspp-registry/blob/566b42a192496caabbcb9207944cff8a22a24841/spp_idqueue/wizard/multi_id_request_wizard.py#L48) *[fixed]*

**Comment by nhatnm0612** [comment]
**spp_change_request**: several errors made the test running fails:
- `test_05_assign_to_user` : failed by [this line of code](https://github.com/OpenSPP/openspp-registry/blob/566b42a192496caabbcb9207944cff8a22a24841/spp_change_request/models/change_request.py#L619) *[fixed]*

**Review by reichie020212 — DISMISSED** [review]

**Review by gonzalesedwin1123 — DISMISSED** [review]

**Review by emjay0921 — DISMISSED** [review]

**Comment by nhatnm0612** [comment]
**spp_consent**: fix consent_mixin create 2 wizard records when open wizard with group: failed by [this line of code](https://github.com/OpenSPP/openspp-registry/blob/566b42a192496caabbcb9207944cff8a22a24841/spp_consent/models/consent_mixin.py#L21) *[fixed]*

**Review by reichie020212 — APPROVED** [review]

**Review by gonzalesedwin1123 — APPROVED** [review]

**Review by emjay0921 — APPROVED** [review]

**Review by jeremi — APPROVED** [review]

**Pull request merged**
