### PR TITLE
add translation for lao

### PR DESCRIPTION
**Pull request by emjay0921**

### CODE REVIEW

**Review by gonzalesedwin1123 — APPROVED** [review]

**Comment by gonzalesedwin1123** [comment]
@emjay0921 please fix the pre-commit errors

**Comment by reichie020212** [comment]
@emjay0921 fix the pre-commit error. execute `pre-commit run -a`

**Review by reichie020212 — CHANGES_REQUESTED** [review]
@emjay0921 fix the pre-commit error. execute pre-commit run -a

**Comment by reichie020212** [comment]
@emjay0921 please pull the new commits in branch 17.0 for the test with odoo check to pass

**Review by reichie020212 — APPROVED** [review]

**Pull request merged**
