### PR TITLE
Fixed issue on spp_user_role where expired account have an access err…

### LINKED ISSUE #423: Improve error message when user account is expired and unable to login
The error message needs to be improved for a user, when logging in with an expired user account in openspp test instance

for example, a simple error message in login screen: Your account has already expired , please contact admin for more information and support

Video link attached for reference:
https://drive.google.com/file/d/1iKisuLzcc1w9AOQlWIubFeNjZ_eFQeyI/view?usp=sharing

Investigation - Red
- This functionality is developed by OCA so I think the error can be improve by either OpenSPP or OpenG2P guys

### PR DESCRIPTION
**Pull request by reichie020212**
…or that doesn't have a good UI

## **Why is this change needed?**

Error message when a user expired doesn't have a good UI

## **How was the change implemented?**

Fix the issue on expired user.

## **New unit tests**

None

## **Unit tests executed by the author**

None

## **How to test manually**

- login your admin account
- Install spp_user_role module
- Go to Settings -> User & Companies -> Users
- Create a new User and add a password. Then Save.

Test 1
- in Roles tab, add a Role, preferably System Admin Role. make sure that the date inputted is within the current date.
- Login the new user in a separate browser or in incognito.
- Check if there is no error and can be login.

Test 2
- Log out the new User and login again.
- Check if there is no error upon logging in.

## **Related links**
https://github.com/OpenSPP/openspp-modules/issues/423

### CODE REVIEW

**Review by gonzalesedwin1123 — COMMENTED** [review]
@reichie020212 can you check also the codecov errors.

**Comment by kneckinator** [comment]
@reichie020212 the PR is awaiting your comments/feedback. Can you please take a look?

**Comment by reichie020212** [comment]
Hi @kneckinator @gonzalesedwin1123 , checking on the comments now. will update once done.

**Comment by reichie020212** [comment]
@kneckinator @gonzalesedwin1123 done fixing the code coverage

**Review by gonzalesedwin1123 — APPROVED** [review]

**Review by emjay0921 — APPROVED** [review]

**Pull request merged**
