### PR TITLE
89 fix area import

### LINKED ISSUE #89: Fix Area Import
**Issue Description**

- The areas import functionality is currently not working as expected. It needs to be fixed to ensure proper data import.

- **Action Item**: Import a sample dataset using 'humdata' to test and validate the import process.

- **Naming Convention Issue**: The root name for imported areas should be 'Sri Lanka' instead of '- Sri Lanka'. This needs correction to maintain consistency and accuracy in data representation.

- **Structure Visualization**: There's an issue with how the structure is displayed post-import. It should be shown properly, reflecting the correct hierarchical of the data.

**Expected Outcome**

- Successful import of the dataset.
- Correct naming convention.
- Proper structural representation in the interface.

### PR DESCRIPTION
**Pull request by reichie020212**
- Fixed naming convention of area
- Fixed, Optimized, and Rewritten the area import

### CODE REVIEW

**Review by gonzalesedwin1123 — APPROVED** [review]

**Comment by jeremi** [comment]
can we add tests for this method:
https://app.codecov.io/gh/OpenSPP/openspp-registry/pull/292/blob/spp_area/models/area_import.py#L257

**Review by jeremi — CHANGES_REQUESTED** [review]
Can we write tests for `validate_raw_data`?
Can we also fix the issue with numpy? we need to upgrade the version there is a vulnerability in the current one. we need at least 
numpy@1.22.2

**Comment by jeremi** [comment]
and @reichie020212 fix pre-commit errors as well.

**Comment by reichie020212** [comment]
> can we add tests for this method: https://app.codecov.io/gh/OpenSPP/openspp-registry/pull/292/blob/spp_area/models/area_import.py#L257

@jeremi Done adding test cases for this method

**Comment by reichie020212** [comment]
> Can we write tests for `validate_raw_data`? Can we also fix the issue with numpy? we need to upgrade the version there is a vulnerability in the current one. we need at least numpy@1.22.2

@jeremi Done adding tests for validate_raw_data and i also added test case for save_to_area.
Done adding numpy with version greater than or equal to 1.22.2 in __manifest__.py and in requirements.txt

**Comment by reichie020212** [comment]
> and @reichie020212 fix pre-commit errors as well.

@jeremi Done fixing pre-commit errors.

**Review by emjay0921 — APPROVED** [review]

**Review by jeremi — APPROVED** [review]

**Comment by jeremi** [comment]
@reichie020212 Can we merge this to 17?

**Comment by reichie020212** [comment]
> @reichie020212 Can we merge this to 17?

@jeremi based on the content of the PR, no it can't be merge to 17, but I can create a separate PR for this fix that can be merge to 17.

**Comment by jeremi** [comment]
@reichie020212 yes, let's have it for branch 17

**Pull request merged**
